### ISSUE TITLE
credentials.json

### ISSUE THREAD

**Issue by alamia442** [LivingWithHippos/unchained-bot#1]
how to create credentials.json?

**Comment by LivingWithHippos** [comment]
Hello,
you need to type `/login` in the telegram chat with the bot, and it will start the procedure to obtain the credentials. The file is managed automatically.

**Comment by alamia442** [comment]
`Traceback (most recent call last):
  File "unchained-bot.py", line 334, in <module>
    main()
  File "unchained-bot.py", line 285, in main
    real_debrid.check_credentials()
AttributeError: module 'debrid.real_debrid_api' has no attribute 'check_credentials'`

error when running python3 unchained-bot.py

**Comment by LivingWithHippos** [comment]
Thanks, I forgot I was in the middle of a refactoring and left the project as it was (not working). 

I've now updated it and it should be working, keep in mind this is a work in progress and it's neither completed nor bug-free. 

Credentials.json is not used anymore, everything is saved inside of user_data/unchaindb (you can explore it with https://sqlitebrowser.org/ for example).

Use `/help` to see available commands and `/login` to start the authentication process the first time you use the bot.

Any feedback will be appreciated
